### ISSUE TITLE
Proposed changes

### ISSUE THREAD

**Issue by rogerthomas84** [LasticotSoftware/Astibot#12]
@LasticotSoftware - I'm contemplating changing the way this works slightly.

I think if you (or I'll be happy to do it) add a simple txt or JSON file with the defined currencies we could change the instructions on the README to say something like...

> Copy the `currencies.example.json` file to `currencies.json` and add or remove trading pairs that you'd like to work with.

Just thinking then the `currencies.json` file can be added to the `.gitignore` file so that other users can make easier changes to the code to propose bug fixes.

Would be keen to know your thoughts. Like I said, I'm more than happy to do that change.

**Comment by Jamonek** [comment]
Have you created the change?

**Comment by rogerthomas84** [comment]
> Have you created the change? 

No, I ended up adding a currencies object (it was merged). The only thing you'd need to do is handle the rounding of the numbers before sending orders I believe. Unfortunately I've had quite a lot happen this year and parked this. My code change is referenced here:

https://github.com/LasticotSoftware/Astibot/blob/master/src/GDAXCurrencies.py
