### ISSUE TITLE
Resume ?

### ISSUE THREAD

**Issue by alexdabast** [LasticotSoftware/Astibot#2]
Hi what happen if the bot crash or lost internet connection but had buy some crypto just before ?
Will it resume his trading process ?

**Comment by LasticotSoftware** [comment]
Hi,

In case of connection loss, the trading process does not stop. It keeps running with the last price retrieved just before the Internet connection shutdown. In background, the bot tries to restart (reopen) the socket connexion in the Coinbase Pro driver (see on_close() in GDAXControler.py). Once Internet is back, trading will work again normally.

In case of a crash, the bot will not resume its trading process on re-launch.
