### ISSUE TITLE
Need to add consideration for buy fees

### ISSUE THREAD

**Issue by ilikenwf** [LasticotSoftware/Astibot#3]
Coinbase pro now charges the same percentage for buys and sells, except in certain cases.

**Comment by ilikenwf** [comment]
https://blog.coinbase.com/updates-to-coinbase-pro-fee-structure-b3d9ee586108

**Comment by LasticotSoftware** [comment]
Thank you.

Added in today's commit (0.5% default fee for both order types)

**Comment by ilikenwf** [comment]
I added some of the other pairs and things, if time permits I'll submit a few pulls someday. Thanks for the hard work!

**Comment by LasticotSoftware** [comment]
Nice, feel free to contribute!
I also added BCH-BTC, ETH-BTC and LTC-BTC pairs in today's commits.
