### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by GettingTechnicl** [LasticotSoftware/Astibot#4]
There were a few extra dependencies not listed in the guide

ipdb
scipy
twilio
tzlocal
gdax

also your run command is python even though you specified python 3 as dependency, but I am running this using "python3 Astibot.py"

**Comment by rayjanoka** [comment]
```
pip3 install pyqt5 pyqtgraph tzlocal cbpro twilio scipy ipdb
```

**Comment by LasticotSoftware** [comment]
Thank you for your feedbacks, Readme.md updated
